-- ============================================================
-- OMELO 16 — Skill taxonomy for the launch categories
-- Weighted toward trades and manual work, not knowledge work.
-- ============================================================

insert into skills (slug, name, type) values
-- Delivery
('two-wheeler-riding','Two-wheeler riding','physical'),
('route-navigation','Route navigation','method'),
('gps-navigation-apps','GPS navigation apps','tool'),
('parcel-handling','Parcel handling','method'),
('cash-on-delivery','Cash on delivery handling','method'),
('local-area-knowledge','Local area knowledge','domain'),
('smartphone-use','Smartphone use','tool'),
('delivery-scheduling','Delivery scheduling','method'),
-- Warehousing
('inventory-management','Inventory management','method'),
('order-picking','Order picking','method'),
('packing','Packing','method'),
('forklift-operation','Forklift operation','equipment'),
('pallet-jack-operation','Pallet jack operation','equipment'),
('stock-counting','Stock counting','method'),
('barcode-scanning','Barcode scanning','tool'),
('loading-unloading','Loading and unloading','physical'),
('heavy-lifting','Heavy lifting','physical'),
('warehouse-safety','Warehouse safety','safety'),
('dispatch-coordination','Dispatch coordination','method'),
-- Retail
('cash-handling','Cash handling','method'),
('pos-operation','POS operation','tool'),
('customer-service','Customer service','soft'),
('merchandising','Merchandising','method'),
('stock-replenishment','Stock replenishment','method'),
('upselling','Upselling','soft'),
('billing','Billing','method'),
('store-opening-closing','Store opening and closing','method'),
-- Food and restaurant
('food-preparation','Food preparation','trade'),
('indian-cuisine','Indian cuisine','domain'),
('chinese-cuisine','Chinese cuisine','domain'),
('continental-cuisine','Continental cuisine','domain'),
('tandoor','Tandoor','equipment'),
('grill-cooking','Grill cooking','equipment'),
('food-safety-hygiene','Food safety and hygiene','safety'),
('knife-skills','Knife skills','trade'),
('menu-knowledge','Menu knowledge','domain'),
('order-taking','Order taking','method'),
('table-service','Table service','method'),
('barista-skills','Barista skills','trade'),
('dishwashing','Dishwashing','method'),
('portion-control','Portion control','method'),
('kitchen-hygiene','Kitchen hygiene','safety'),
-- Security
('access-control','Access control','method'),
('cctv-monitoring','CCTV monitoring','tool'),
('patrolling','Patrolling','method'),
('visitor-management','Visitor management','method'),
('emergency-response','Emergency response','safety'),
('fire-safety','Fire safety','safety'),
('crowd-control','Crowd control','method'),
('incident-reporting','Incident reporting','administrative'),
-- Transportation
('light-vehicle-driving','Light vehicle driving','physical'),
('heavy-vehicle-driving','Heavy vehicle driving','physical'),
('defensive-driving','Defensive driving','method'),
('vehicle-maintenance-basics','Basic vehicle maintenance','trade'),
('route-planning','Route planning','method'),
('logbook-maintenance','Logbook maintenance','administrative'),
-- Construction and trades
('masonry','Masonry','trade'),
('plastering','Plastering','trade'),
('tiling','Tiling','trade'),
('carpentry','Carpentry','trade'),
('electrical-wiring','Electrical wiring','trade'),
('plumbing','Plumbing','trade'),
('welding','Welding','trade'),
('painting','Painting','trade'),
('scaffolding','Scaffolding','trade'),
('rebar-work','Rebar work','trade'),
('concrete-work','Concrete work','trade'),
('power-tools','Power tools','equipment'),
('hand-tools','Hand tools','equipment'),
('blueprint-reading','Blueprint reading','method'),
('site-safety','Site safety','safety'),
('measuring-levelling','Measuring and levelling','method'),
-- Cleaning and domestic
('floor-cleaning','Floor cleaning','method'),
('deep-cleaning','Deep cleaning','method'),
('chemical-handling','Cleaning chemical handling','safety'),
('waste-disposal','Waste disposal','method'),
('housekeeping','Housekeeping','method'),
('laundry','Laundry','method'),
('home-cooking','Home cooking','trade'),
('childcare','Childcare','domain'),
('elderly-care','Elderly care','domain'),
-- Automotive
('engine-repair','Engine repair','trade'),
('brake-systems','Brake systems','trade'),
('auto-ac-repair','Auto AC repair','trade'),
('auto-electrical','Auto electrical','trade'),
('two-wheeler-repair','Two-wheeler repair','trade'),
('denting-painting','Denting and painting','trade'),
('vehicle-diagnostics','Vehicle diagnostics','tool'),
-- Healthcare
('patient-care','Patient care','domain'),
('vital-signs-monitoring','Vital signs monitoring','method'),
('injections','Injections','trade'),
('first-aid','First aid','safety'),
('medical-records','Medical records','administrative'),
('infection-control','Infection control','safety'),
-- Administrative and customer service
('data-entry','Data entry','administrative'),
('ms-excel','MS Excel','tool'),
('typing','Typing','administrative'),
('telephone-handling','Telephone handling','soft'),
('email-handling','Email handling','administrative'),
('record-keeping','Record keeping','administrative'),
('scheduling','Scheduling','method'),
-- Technology
('javascript','JavaScript','technical'),
('python','Python','technical'),
('flutter','Flutter','technical'),
('react','React','technical'),
('sql','SQL','technical'),
('git','Git','tool'),
('rest-apis','REST APIs','technical'),
('cloud-basics','Cloud fundamentals','technical'),
-- Universal
('teamwork','Teamwork','soft'),
('punctuality','Punctuality','soft'),
('communication','Communication','soft'),
('problem-solving','Problem solving','soft'),
('physical-stamina','Physical stamina','physical'),
('attention-to-detail','Attention to detail','soft'),
('supervision','Supervision','soft'),
('hindi-communication','Hindi communication','language'),
('english-communication','English communication','language');

-- ------------------------------------------------------------
-- profession -> skill importance (0..1)
-- ------------------------------------------------------------
insert into profession_skills (profession_id, skill_id, importance, source)
select p.id, s.id, v.importance, 'admin'
from (values
  ('delivery-executive','two-wheeler-riding',1.00),
  ('delivery-executive','route-navigation',0.90),
  ('delivery-executive','gps-navigation-apps',0.85),
  ('delivery-executive','smartphone-use',0.85),
  ('delivery-executive','parcel-handling',0.80),
  ('delivery-executive','cash-on-delivery',0.75),
  ('delivery-executive','local-area-knowledge',0.80),
  ('delivery-executive','customer-service',0.65),
  ('delivery-executive','punctuality',0.80),
  ('courier','parcel-handling',0.95),
  ('courier','route-navigation',0.90),
  ('courier','local-area-knowledge',0.80),
  ('courier','two-wheeler-riding',0.75),
  ('courier','punctuality',0.80),

  ('warehouse-worker','order-picking',0.95),
  ('warehouse-worker','packing',0.90),
  ('warehouse-worker','loading-unloading',0.85),
  ('warehouse-worker','stock-counting',0.80),
  ('warehouse-worker','barcode-scanning',0.75),
  ('warehouse-worker','heavy-lifting',0.80),
  ('warehouse-worker','warehouse-safety',0.85),
  ('warehouse-worker','physical-stamina',0.75),
  ('packer','packing',1.00),
  ('packer','attention-to-detail',0.85),
  ('packer','stock-counting',0.70),
  ('packer','physical-stamina',0.65),
  ('warehouse-supervisor','inventory-management',0.95),
  ('warehouse-supervisor','supervision',0.95),
  ('warehouse-supervisor','dispatch-coordination',0.85),
  ('warehouse-supervisor','warehouse-safety',0.90),
  ('warehouse-supervisor','record-keeping',0.70),
  ('forklift-operator','forklift-operation',1.00),
  ('forklift-operator','warehouse-safety',0.90),
  ('forklift-operator','pallet-jack-operation',0.70),
  ('forklift-operator','loading-unloading',0.75),

  ('cashier','cash-handling',1.00),
  ('cashier','pos-operation',0.95),
  ('cashier','billing',0.85),
  ('cashier','customer-service',0.85),
  ('cashier','attention-to-detail',0.80),
  ('sales-assistant','customer-service',0.95),
  ('sales-assistant','upselling',0.80),
  ('sales-assistant','merchandising',0.70),
  ('sales-assistant','stock-replenishment',0.70),
  ('sales-assistant','communication',0.85),
  ('stock-clerk','stock-replenishment',0.95),
  ('stock-clerk','stock-counting',0.90),
  ('stock-clerk','inventory-management',0.75),
  ('store-manager','supervision',0.95),
  ('store-manager','inventory-management',0.85),
  ('store-manager','store-opening-closing',0.85),
  ('store-manager','customer-service',0.80),

  ('cook','food-preparation',1.00),
  ('cook','indian-cuisine',0.85),
  ('cook','knife-skills',0.85),
  ('cook','food-safety-hygiene',0.90),
  ('cook','portion-control',0.70),
  ('chef','food-preparation',1.00),
  ('chef','menu-knowledge',0.90),
  ('chef','supervision',0.85),
  ('chef','food-safety-hygiene',0.95),
  ('chef','portion-control',0.85),
  ('chef','knife-skills',0.90),
  ('kitchen-helper','food-preparation',0.80),
  ('kitchen-helper','kitchen-hygiene',0.90),
  ('kitchen-helper','dishwashing',0.75),
  ('kitchen-helper','physical-stamina',0.70),
  ('dishwasher','dishwashing',1.00),
  ('dishwasher','kitchen-hygiene',0.90),
  ('dishwasher','physical-stamina',0.70),
  ('waiter','table-service',1.00),
  ('waiter','order-taking',0.95),
  ('waiter','menu-knowledge',0.85),
  ('waiter','customer-service',0.90),
  ('waiter','communication',0.85),
  ('barista','barista-skills',1.00),
  ('barista','customer-service',0.85),
  ('barista','cash-handling',0.70),
  ('barista','food-safety-hygiene',0.80),

  ('security-guard','patrolling',0.95),
  ('security-guard','access-control',0.95),
  ('security-guard','visitor-management',0.85),
  ('security-guard','incident-reporting',0.80),
  ('security-guard','emergency-response',0.85),
  ('security-guard','fire-safety',0.75),
  ('security-supervisor','supervision',0.95),
  ('security-supervisor','cctv-monitoring',0.85),
  ('security-supervisor','emergency-response',0.90),
  ('security-supervisor','incident-reporting',0.85),
  ('security-supervisor','crowd-control',0.75),

  ('driver','light-vehicle-driving',1.00),
  ('driver','defensive-driving',0.85),
  ('driver','route-planning',0.80),
  ('driver','vehicle-maintenance-basics',0.65),
  ('driver','punctuality',0.85),
  ('truck-driver','heavy-vehicle-driving',1.00),
  ('truck-driver','defensive-driving',0.90),
  ('truck-driver','logbook-maintenance',0.70),
  ('truck-driver','route-planning',0.85),
  ('taxi-driver','light-vehicle-driving',1.00),
  ('taxi-driver','local-area-knowledge',0.90),
  ('taxi-driver','gps-navigation-apps',0.80),
  ('taxi-driver','customer-service',0.75),
  ('bus-driver','heavy-vehicle-driving',1.00),
  ('bus-driver','defensive-driving',0.90),
  ('bus-driver','punctuality',0.85),

  ('electrician','electrical-wiring',1.00),
  ('electrician','site-safety',0.90),
  ('electrician','blueprint-reading',0.70),
  ('electrician','hand-tools',0.85),
  ('electrician','power-tools',0.80),
  ('plumber','plumbing',1.00),
  ('plumber','hand-tools',0.85),
  ('plumber','site-safety',0.80),
  ('mason','masonry',1.00),
  ('mason','plastering',0.85),
  ('mason','concrete-work',0.80),
  ('mason','measuring-levelling',0.75),
  ('carpenter','carpentry',1.00),
  ('carpenter','power-tools',0.90),
  ('carpenter','measuring-levelling',0.80),
  ('carpenter','hand-tools',0.85),
  ('welder','welding',1.00),
  ('welder','site-safety',0.90),
  ('welder','blueprint-reading',0.65),
  ('painter','painting',1.00),
  ('painter','site-safety',0.75),
  ('general-laborer','physical-stamina',0.95),
  ('general-laborer','heavy-lifting',0.90),
  ('general-laborer','site-safety',0.85),
  ('general-laborer','hand-tools',0.60),
  ('site-supervisor','supervision',1.00),
  ('site-supervisor','site-safety',0.95),
  ('site-supervisor','blueprint-reading',0.85),
  ('site-supervisor','record-keeping',0.70),
  ('scaffolder','scaffolding',1.00),
  ('scaffolder','site-safety',0.95),
  ('scaffolder','physical-stamina',0.80),

  ('cleaner','floor-cleaning',0.95),
  ('cleaner','deep-cleaning',0.85),
  ('cleaner','chemical-handling',0.80),
  ('cleaner','waste-disposal',0.75),
  ('janitor','floor-cleaning',0.90),
  ('janitor','waste-disposal',0.85),
  ('janitor','chemical-handling',0.75),
  ('housekeeper','housekeeping',1.00),
  ('housekeeper','laundry',0.80),
  ('housekeeper','deep-cleaning',0.80),
  ('domestic-helper','housekeeping',0.90),
  ('domestic-helper','laundry',0.80),
  ('domestic-helper','home-cooking',0.70),
  ('cook-domestic','home-cooking',1.00),
  ('cook-domestic','indian-cuisine',0.85),
  ('cook-domestic','food-safety-hygiene',0.75),
  ('nanny','childcare',1.00),
  ('nanny','first-aid',0.70),
  ('caregiver','elderly-care',0.95),
  ('caregiver','patient-care',0.85),
  ('caregiver','first-aid',0.80),

  ('auto-mechanic','engine-repair',0.95),
  ('auto-mechanic','brake-systems',0.90),
  ('auto-mechanic','vehicle-diagnostics',0.80),
  ('auto-mechanic','hand-tools',0.85),
  ('auto-electrician','auto-electrical',1.00),
  ('auto-electrician','vehicle-diagnostics',0.85),

  ('nurse','patient-care',1.00),
  ('nurse','vital-signs-monitoring',0.95),
  ('nurse','injections',0.90),
  ('nurse','infection-control',0.90),
  ('nurse','medical-records',0.75),
  ('ward-attendant','patient-care',0.90),
  ('ward-attendant','infection-control',0.85),
  ('ward-attendant','physical-stamina',0.75),

  ('data-entry-operator','data-entry',1.00),
  ('data-entry-operator','typing',0.90),
  ('data-entry-operator','ms-excel',0.80),
  ('data-entry-operator','attention-to-detail',0.85),
  ('office-assistant','record-keeping',0.85),
  ('office-assistant','ms-excel',0.75),
  ('office-assistant','telephone-handling',0.75),
  ('receptionist','telephone-handling',0.95),
  ('receptionist','visitor-management',0.90),
  ('receptionist','communication',0.90),
  ('call-centre-agent','telephone-handling',1.00),
  ('call-centre-agent','communication',0.95),
  ('call-centre-agent','customer-service',0.90),

  ('software-engineer','javascript',0.80),
  ('software-engineer','python',0.75),
  ('software-engineer','sql',0.80),
  ('software-engineer','git',0.85),
  ('software-engineer','rest-apis',0.85),
  ('software-engineer','problem-solving',0.90),
  ('mobile-developer','flutter',0.85),
  ('mobile-developer','rest-apis',0.85),
  ('mobile-developer','git',0.85)
) as v(prof, skill, importance)
join professions p on p.slug = v.prof
join skills s on s.slug = v.skill;